# Generated by Django 2.1.5 on 2019-07-20 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('aage', models.IntegerField()),
                ('aexperience', models.IntegerField()),
                ('anoOfMovies', models.IntegerField()),
                ('aaddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'actor_Info',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('line1', models.CharField(max_length=50)),
                ('line2', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'country_Info',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('dage', models.IntegerField()),
                ('dexperience', models.IntegerField()),
                ('dnoOfMovies', models.IntegerField()),
                ('daddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'director_Info',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('noSongs', models.CharField(max_length=50)),
                ('releasedate', models.DateField(default=datetime.date.today)),
                ('actors', models.ManyToManyField(to='movieapp.Actor')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Country')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Director')),
            ],
            options={
                'db_table': 'movie_Info',
            },
        ),
    ]
